- hosts: security_group_web_server_dmz
  become: true
  tasks:
  
  - name: Remove previous code
    file:
      path: /var/www/html/website
      state: absent

  - git:
      repo: https://github.com/manikcloud/varun_medium_cicd_code.git
      dest: /var/www/html/website
